spring.application.name=kwube
server.port=${PORT:8080}

spring.config.import=optional:file:.env[.properties]
kwube.weatherapi.baseurl=${WEATHER_API_BASE_URL}
kwube.weatherapi.key=${WEATHER_API_KEY}
kwube.geminiapi.key=${GEMINI_API_KEY}
kwube.exchangerateapi.baseurl=${EXCHANGE_RATE_BASE_URL}
kwube.exchangerateapi.key=${EXCHANGE_RATE_API_KEY}

# Spring profile
spring.profiles.active=${SPRING_PROFILE:prod}

#For swagger docs production
springdoc.openapi.servers[0].url=${SWAGGER_SERVER_URL:http://localhost:8080}