spring.application.name=kwube
spring.config.import=file:.env[.properties]
kwube.weatherapi.baseurl=${WEATHER_API_BASE_URL}
kwube.weatherapi.key=${WEATHER_API_KEY}
kwube.geminiapi.key=${GEMINI_API_KEY}
kwube.exchangerateapi.baseurl=${EXCHANGE_RATE_BASE_URL}
kwube.exchangerateapi.key=${EXCHANGE_RATE_API_KEY}
kwube.elevenlabsapi.key=${ELEVENLABS_API_KEY}
kwube.elevenlabs.voiceid=${ELEVENLABS_VOICE_ID}
kwube.elevenlabs.baseurl=${ELEVENLABS_BASE_URL}