spring.application.name=kwube
spring.config.import=file:.env[.properties]
kwube.weatherapi.baseurl=${WEATHER_API_BASE_URL}
kwube.weatherapi.key=${WEATHER_API_KEY}
kwube.geminiapi.key=${GEMINI_API_KEY}